name: My GO Fortune Workflow

#trigger 
on: 
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
# Jobs in the workflow
jobs:
  # job name
  my-first-attempt-to-test-if-YAML-works:
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    # OS that this workflow will be running on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
  # list of steps to perform task
    steps:   
    - name: Checkout the current repo
      id: step1 
      run: echo " ${{github.event.head_commit.message}} "
    - name: Checkout the current repo
      id: step2
      uses: actions/checkout@v3
    - name: Install Node so that Railway can run
      id: step3
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway on Github Terminal
      id: step4
      run: npm i -g @railway/cli
    - name: Deploy
      id: step5 
      run: echo railwayup_outcome=$(railway up) >> $GITHUB_OUTPUT
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Get substring
      id: step6 
      run: echo mod_railwayup_outcome=${{steps.step5.outputs.railwayup_outcome}} | awk '{ sub(/.*Deployment live at:/, ""); print }' >> $GITHUB_OUTPUT
    - uses: ncipollo/release-action@v1
      id: step7
      with:
        tag: ${{ github.ref_name }}
        commit: ${{ github.ref_name }}
        token: ${{ secrets.GH_TOKEN }}
    - name: Send test data to Slack workflow
      id: step8
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nLin Shanfu\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA0043752J"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne1048846@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{github.repositoryUrl}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n ${{toJSON(steps.step6.outputs.railwayup_outcome)}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "<https://linshanfugolangassignment-production.up.railway.app/| Open Application>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      #uses: actions/checkout@v3
      #with:
      #  ref: " ${{ github.ref }} "
    #- name: List my current directory after checkout
    #  run: ls -l


