name: My GO Fortune Workflow

#trigger 
on: 
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
# Jobs in the workflow
jobs:
  # job name
  my-first-attempt-to-test-if-YAML-works:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
  # list of steps to perform task
    steps:   
    - name: Checkout the current repo
      run: echo " The current time and date in Github is $(date)"
    - name: Checkout the current repo
      uses: actions/checkout@v3
    - name: Install Node so that Railway can run
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway on Github Terminal
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        commit: ${{ github.ref }}
        artifacts: "release.tar.gz,foo/*.txt"
        token: ${{ secrets.GH_TOKEN }}
    - name: Send test data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "This is just a test",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Testing 123"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      #uses: actions/checkout@v3
      #with:
      #  ref: " ${{ github.ref }} "
    #- name: List my current directory after checkout
    #  run: ls -l


