name: My GO Fortune Workflow

#trigger 
on: 
  push
# Jobs in the workflow
jobs:
  # job name
  my-first-attempt-to-test-if-YAML-works:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

  # list of steps to perform task
    steps:   
    - name: Checkout the current repo
      run: echo " The current time and date in Github is $(date)"
    - name: Send test data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      #uses: actions/checkout@v3
      #with:
      #  ref: " ${{ github.ref }} "
    #- name: List my current directory after checkout
    #  run: ls -l


